# Generated by Django 5.1.6 on 2025-11-25 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilhas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trilha',
            name='author',
            field=models.ForeignKey(help_text='Instrutor responsável pela trilha', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trilhas_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trilha',
            name='category',
            field=models.CharField(choices=[('Fundamentos', 'Fundamentos'), ('Front-end', 'Front-end'), ('Back-end', 'Back-end'), ('DevOps', 'DevOps'), ('Mobile', 'Mobile'), ('Dados', 'Banco de Dados')], default='Fundamentos', help_text='Categoria para filtro na Home', max_length=50),
        ),
        migrations.AddField(
            model_name='trilha',
            name='duration',
            field=models.CharField(default='0h 00m', help_text='Duração estimada (ex: 2h 30m)', max_length=20),
        ),
        migrations.AddField(
            model_name='trilha',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagem de capa do card (proporção ideal 16:9)', null=True, upload_to='trilhas/covers/'),
        ),
    ]
