# Generated by Django 5.1.6 on 2025-11-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilhas', '0002_trilha_author_trilha_category_trilha_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='duration',
            field=models.CharField(blank=True, help_text='Duração estimada (ex: 10 min)', max_length=20),
        ),
        migrations.AddField(
            model_name='atividade',
            name='type',
            field=models.CharField(choices=[('video', 'Vídeo Aula'), ('text', 'Leitura / Artigo'), ('quiz', 'Quiz / Desafio')], default='text', help_text='Define o ícone no frontend', max_length=20),
        ),
        migrations.AddField(
            model_name='atividade',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link do Youtube/Vimeo (se for vídeo)', null=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='content',
            field=models.TextField(blank=True, help_text='Conteúdo em texto ou Markdown'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição curta para listagem'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='description',
            field=models.TextField(blank=True, help_text='Breve descrição do que será aprendido neste módulo.'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='order',
            field=models.PositiveIntegerField(help_text='Posição sequencial dentro da trilha (1, 2, 3...).'),
        ),
        migrations.AlterField(
            model_name='trilha',
            name='duration',
            field=models.CharField(default='0h 00m', help_text='Duração estimada total (ex: 2h 30m)', max_length=20),
        ),
    ]
