# Generated by Django 5.1.6 on 2025-10-11 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('arroba', models.CharField(max_length=255, unique=True)),
                ('stack', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('skills', models.CharField(max_length=255)),
                ('xp', models.IntegerField(default=0, editable=False)),
                ('exercicios_concluidos', models.IntegerField(default=0, editable=False)),
                ('trilhas_concluidas', models.IntegerField(default=0, editable=False)),
                ('dias_conectados', models.IntegerField(default=0, editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
